/** @type {import('tailwindcss').Config} */
module.exports = {
	mode: 'jit',
	content: [
		'./src/components/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/theme/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/hooks/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/**/*.{js,ts,jsx,tsx,mdx}',
	],
	safelist: [
		'bg-white',
		'bg-transparent',
		'bg-blue-500',
		'bg-blue-600',
		'bg-blue-900',
		'text-white',
		'text-blue-500',
		'text-blue-600',
		'text-blue-900',
		'hover:bg-blue-100',
		'hover:bg-blue-600',
		'hover:bg-gray-100',
		'hover:text-white',
		'hover:text-black',
		'hover:text-blue-900',
		'w-320',
		'w-640',
		'h-320',
		'h-640',
		'grid-cols-5',
		'grid-rows-5',
	],
	theme: {
		extend: {},
		fontWeight: {
			light: 300,
			normal: 400,
			medium: 500,
			semiBold: 600,
			bold: 700,
			extraBold: 800,
			black: 900,
		},
	},
	plugins: [],
};
